modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/LXGaming/Sumsang/issues"

[[mods]]
modId="sumsang"
version="${version}"
displayName="Sumsang"
# updateJSONURL=""
displayURL="https://lxgaming.github.io/"
logoFile="lxgaming.png"
credits="LX_Gaming"
authors="LX_Gaming"
description="Sumsang\nSource - https://github.com/LXGaming/Sumsang"